/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.lge.spartan.daltest;

import com.lge.spartan.dal.DAL;
import com.lge.spartan.dal.MySQLDALImpl;
import com.lge.spartan.data.Customer;
import com.lge.spartan.data.OrderInfo;
import com.lge.spartan.data.Widget;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author vijay.rachabattuni
 */
public class DALTestForm extends javax.swing.JFrame {
     static DAL dal = null;
    /**
     * Creates new form DALTestForm
     */
    public DALTestForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnInitDB = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jbtnGetWidgets = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jbtnGetCustomers = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jbtnPendingOrders = new javax.swing.JButton();
        jbtnShippingOrders = new javax.swing.JButton();
        jbtnBackorderedOrders = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnInitDB.setText("Initialize DB");
        jbtnInitDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInitDBActionPerformed(evt);
            }
        });

        jbtnGetWidgets.setText("Get Widgets");
        jbtnGetWidgets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGetWidgetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jbtnGetWidgets)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnGetWidgets)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inventory", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Monitor", jPanel2);

        jbtnGetCustomers.setText("Get Customers");
        jbtnGetCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGetCustomersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnGetCustomers)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnGetCustomers)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customers", jPanel3);

        jbtnPendingOrders.setText("Get Pending Orders");
        jbtnPendingOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPendingOrdersActionPerformed(evt);
            }
        });

        jbtnShippingOrders.setText("Get Shipping Orders");
        jbtnShippingOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShippingOrdersActionPerformed(evt);
            }
        });

        jbtnBackorderedOrders.setText("Get Backordered Orders");
        jbtnBackorderedOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackorderedOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnBackorderedOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnShippingOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnPendingOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnPendingOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnShippingOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnBackorderedOrders)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Orders", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jbtnInitDB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jbtnInitDB)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnInitDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInitDBActionPerformed
        // TODO add your handling code here:
        InitDB();
    }//GEN-LAST:event_jbtnInitDBActionPerformed

    private void jbtnPendingOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPendingOrdersActionPerformed
        // TODO add your handling code here:
        ArrayList<OrderInfo> listOI = dal.GetPendingOrders();
        for(OrderInfo oi : listOI)
        {
            System.out.println(oi.toString());
        }
    }//GEN-LAST:event_jbtnPendingOrdersActionPerformed

    private void jbtnGetCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGetCustomersActionPerformed
        // TODO add your handling code here:
        ArrayList<Customer> list = dal.GetCustomers();
        for(Customer c : list)
        {
            System.out.println(c.toString());
        }
    }//GEN-LAST:event_jbtnGetCustomersActionPerformed

    private void jbtnGetWidgetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGetWidgetsActionPerformed
        // TODO add your handling code here:
        ArrayList<Widget> list = dal.GetWidgets();
        for(Widget w : list)
        {
            System.out.println(w.toString());
        }
    }//GEN-LAST:event_jbtnGetWidgetsActionPerformed

    private void jbtnShippingOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShippingOrdersActionPerformed
        // TODO add your handling code here:
         ArrayList<OrderInfo> listOI = dal.GetShippedOrders();
        for(OrderInfo oi : listOI)
        {
            System.out.println(oi.toString());
        }
    }//GEN-LAST:event_jbtnShippingOrdersActionPerformed

    private void jbtnBackorderedOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackorderedOrdersActionPerformed
        // TODO add your handling code here:
           ArrayList<OrderInfo> listOI = dal.GetBackorderedOrders();
        for(OrderInfo oi : listOI)
        {
            System.out.println(oi.toString());
        }
    }//GEN-LAST:event_jbtnBackorderedOrdersActionPerformed

    
    
    private void InitDB() {
        dal = new MySQLDALImpl();
        boolean res = dal.Initialize("127.0.0.1", "root", "");//vijay
        if(res == true)
        {
            JOptionPane.showMessageDialog(this, "DB Init Success11");
        }
        else
            JOptionPane.showMessageDialog(this, "DB Init Failed");
    }
    
     private void UninitDB() {
        boolean res = dal.Uninitialize();
        if(res == true)
        {
            JOptionPane.showMessageDialog(this, "DB Uninit Success");
        }
        else
            JOptionPane.showMessageDialog(this, "DB Uninit Failed");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DALTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DALTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DALTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DALTestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DALTestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnBackorderedOrders;
    private javax.swing.JButton jbtnGetCustomers;
    private javax.swing.JButton jbtnGetWidgets;
    private javax.swing.JButton jbtnInitDB;
    private javax.swing.JButton jbtnPendingOrders;
    private javax.swing.JButton jbtnShippingOrders;
    // End of variables declaration//GEN-END:variables
}
